// 기술 스택 옵션
export const techStacks = [
  { id: "aws", name: "AWS", image: "/Stacks/AWS.svg" },
  { id: "django", name: "Django", image: "/Stacks/Django.svg" },
  { id: "docker", name: "Docker", image: "/Stacks/Docker.svg" },
  { id: "express", name: "Express", image: "/Stacks/Express.svg" },
  { id: "figma", name: "Figma", image: "/Stacks/Figma.svg" },
  { id: "firebase", name: "Firebase", image: "/Stacks/Firebase.svg" },
  { id: "flutter", name: "Flutter", image: "/Stacks/Flutter.svg" },
  { id: "git", name: "Git", image: "/Stacks/Git.svg" },
  { id: "go", name: "Go", image: "/Stacks/Go.svg" },
  { id: "graphql", name: "GraphQL", image: "/Stacks/GraphQL.svg" },
  { id: "java", name: "Java", image: "/Stacks/Java.svg" },
  { id: "javascript", name: "JavaScript", image: "/Stacks/JavaScript.svg" },
  { id: "jest", name: "Jest", image: "/Stacks/Jest.svg" },
  { id: "kotlin", name: "Kotlin", image: "/Stacks/Kotlin.svg" },
  { id: "kubernetes", name: "Kubernetes", image: "/Stacks/Kubernetes.svg" },
  { id: "mongodb", name: "MongoDB", image: "/Stacks/MongoDB.svg" },
  { id: "mysql", name: "MySQL", image: "/Stacks/MySQL.svg" },
  { id: "nestjs", name: "NestJS", image: "/Stacks/Nestjs.svg" },
  { id: "nextjs", name: "NextJS", image: "/Stacks/Nextjs.svg" },
  { id: "nodejs", name: "NodeJS", image: "/Stacks/Nodejs.svg" },
  { id: "php", name: "PHP", image: "/Stacks/Php.svg" },
  { id: "python", name: "Python", image: "/Stacks/Python.svg" },
  { id: "react", name: "React", image: "/Stacks/React.svg" },
  { id: "reactnative", name: "React Native", image: "/Stacks/ReactNative.svg" },
  { id: "spring", name: "Spring", image: "/Stacks/Spring.svg" },
  { id: "svelte", name: "Svelte", image: "/Stacks/Svelte.svg" },
  { id: "swift", name: "Swift", image: "/Stacks/Swift.svg" },
  { id: "typescript", name: "TypeScript", image: "/Stacks/TypeScript.svg" },
  { id: "unity", name: "Unity", image: "/Stacks/Unity.svg" },
  { id: "vue", name: "Vue", image: "/Stacks/Vue.svg" },
  { id: "zeplin", name: "Zeplin", image: "/Stacks/Zeplin.svg" },
];

// 소셜/포트폴리오 링크 플랫폼 옵션
export const platformOptions = [
  { value: "behance", label: "비핸스" },
  { value: "github", label: "깃허브" },
  { value: "instagram", label: "인스타그램" },
  { value: "brunch", label: "브런치" },
  { value: "linkedin", label: "링크드인" },
  { value: "notion", label: "노션" },
  { value: "pinterest", label: "핀터레스트" },
  { value: "medium", label: "미디엄" },
  { value: "tistory", label: "티스토리" },
  { value: "facebook", label: "페이스북" },
  { value: "youtube", label: "유튜브" },
];